USE bikehunt;

DROP TABLE IF EXISTS Login;
DROP TABLE IF EXISTS Spezial;
DROP TABLE IF EXISTS Standort;
DROP TABLE IF EXISTS Team;


CREATE TABLE Team(
    TeamNr INT NOT NULL AUTO_INCREMENT,
    Name VARCHAR(50),
    Beschreibung VARCHAR(250),
    Rolle INT,
    PRIMARY KEY(TeamNr)
);

CREATE TABLE Standort(
    StandortNr INT NOT NULL AUTO_INCREMENT,
    Team INT,
    Zeit TIMESTAMP,
    Laenge FLOAT,
    Breite FLOAT,
    PRIMARY KEY(StandortNr),
    FOREIGN KEY(Team) REFERENCES Team(TeamNr) ON UPDATE CASCADE
);

CREATE TABLE Spezial(
    SpezialNr INT NOT NULL AUTO_INCREMENT,
    Team INT,
    Typ VARCHAR(50),
    Zeit TIMESTAMP,
    PRIMARY KEY(SpezialNr),
    FOREIGN KEY(Team) REFERENCES Team(TeamNr) ON UPDATE CASCADE
);

CREATE TABLE Login(
    LoginNr INT NOT NULL AUTO_INCREMENT,
    Team INT,
    Gegner INT,
    Code VARCHAR(50),
    PRIMARY KEY(LoginNr),
    FOREIGN KEY(Team) REFERENCES Team(TeamNr) ON UPDATE CASCADE,
    FOREIGN KEY(Gegner) REFERENCES Team(TeamNr) ON UPDATE CASCADE
);